version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./php:/var/www/html
      - ./data:/var/www/html/data
    restart: always
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'Health OK';"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    volumes:
      - ./php:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      php:
        condition: service_healthy
    restart: always

  backup:
    image: alpine
    volumes:
      - ./data:/data
      - ./backup:/backup
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while true; do
         mkdir -p /backup/$(date +%Y-%m-%d) &&
         tar czf /backup/$(date +%Y-%m-%d)/sqlite-backup.tar.gz /data &&
         sleep 86400;
       done"
    restart: always