name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  pull_request:
    branches:
      - main   # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu machine

    steps:
    # 1. Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Docker Buildx (for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 3. Login to Docker Hub or GitHub Container Registry (if you want to push the image later)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username (set this as a secret in GitHub)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or personal access token

    # 4. Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t yourusername/your-repo-name .

    # 5. Run tests on the Docker container (optional)
    - name: Run tests on Docker container
      run: |
        docker run --rm yourusername/your-repo-name /bin/bash -c "your-test-command"

    # 6. Optionally push the Docker image to Docker Hub or GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push yourusername/your-repo-name
